name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/hackathon:latest
          ${{ secrets.DOCKER_USERNAME }}/hackathon:${{ github.sha }}
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Docker가 설치되어 있는지 확인
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed"
            exit 1
          fi
          
          # 기존 컨테이너 중지 및 제거
          sudo docker stop hackathon-app || true
          sudo docker rm hackathon-app || true
          
          # 기존 이미지 제거
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/hackathon:latest || true
          
          # 새 이미지 pull
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hackathon:latest
          
          # 새 컨테이너 실행
          sudo docker run -d \
            --name hackathon-app \
            -p 80:3000 \
            --restart unless-stopped \
            ${{ secrets.DOCKER_USERNAME }}/hackathon:latest
          
          # 컨테이너 상태 확인
          sudo docker ps
          
          # 사용하지 않는 이미지 정리
          sudo docker image prune -f